version: '3.9'

services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - OWNCLOUD_DB_TYPE=pgsql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USER=owncloud
      - OWNCLOUD_DB_PASSWORD=securepassword
      - OWNCLOUD_DB_HOST=postgres
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - owncloud_data:/mnt/data

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: owncloud
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: owncloud
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--requirepass", "securepassword"]
    environment:
      - REDIS_PASSWORD=securepassword
    volumes:
      - redis_data:/data

volumes:
  owncloud_data:
  postgres_data:
  redis_data:
